### ISSUE TITLE
radio button 구현 및 이벤트함수 적용

### ISSUE THREAD

**Issue by SuperH0ng** [Honghyeonji/react_study#11]
inputs.js에서 question, answer  map으로 구현 및 update, result 함수 적용하기

**Comment by SuperH0ng** [comment]
personalityTest.PersonalityTest에 전달되는 onUpdate, onresult가 메서드로 전달되는게 맞는지 모르겠음... ㅜ

inputs에서 호출한 answerList에서 onUpdate함수를 사용했는데 아래와 같은 오류가 뜸
![image](https://user-images.githubusercontent.com/81635179/147861071-1b233cec-787e-4c98-8b71-a113cc22a8bd.png)

![image](https://user-images.githubusercontent.com/81635179/147861047-248efa8e-ba46-4e19-a20d-65babae2447b.png)

**Comment by SuperH0ng** [comment]
다른 방식으로 TestActions.update를 직접 적용하려고 하였는데
![image](https://user-images.githubusercontent.com/81635179/147861096-508846e8-bea9-42b8-b067-6d79a92d93ab.png)
아래와 같이 무한루프 오류가 발생..
![image](https://user-images.githubusercontent.com/81635179/147861102-3ab650be-f878-4e72-947a-d35666cd979e.png)

**Comment by Honghyeonji** [comment]
ducks pattern을 container를 통해 바인딩하는 방식을 쓰는 것보다 간결화 시켜서 useDispatch를 사용해 이벤트 메소드를 계속 인자로 넘기지 않고 Answer.js에서 바로 모듈의 액션에 접근하게 함.

**Comment by Honghyeonji** [comment]
ducks pattern - https://velog.io/@tlatjdgh3778/React-Redux-Ducks-Pattern-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0
ducks pattern - https://dinn.github.io/web/redux-ducks-pattern/
